# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Database.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x44\x61tabase.proto\x12\x08\x64\x61tabase\"!\n\x10GetRecordRequest\x12\r\n\x05index\x18\x01 \x01(\x05\"1\n\x11GetRecordResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"0\n\x10\x41\x64\x64RecordRequest\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"\x1f\n\x11\x41\x64\x64RecordResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x10\n\x0eGetSizeRequest\"\x1f\n\x0fGetSizeResponse\x12\x0c\n\x04size\x18\x01 \x01(\x05\x32\xdc\x01\n\x08\x44\x61tabase\x12\x46\n\tGetRecord\x12\x1a.database.GetRecordRequest\x1a\x1b.database.GetRecordResponse\"\x00\x12\x46\n\tAddRecord\x12\x1a.database.AddRecordRequest\x1a\x1b.database.AddRecordResponse\"\x00\x12@\n\x07GetSize\x12\x18.database.GetSizeRequest\x1a\x19.database.GetSizeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETRECORDREQUEST']._serialized_start=28
  _globals['_GETRECORDREQUEST']._serialized_end=61
  _globals['_GETRECORDRESPONSE']._serialized_start=63
  _globals['_GETRECORDRESPONSE']._serialized_end=112
  _globals['_ADDRECORDREQUEST']._serialized_start=114
  _globals['_ADDRECORDREQUEST']._serialized_end=162
  _globals['_ADDRECORDRESPONSE']._serialized_start=164
  _globals['_ADDRECORDRESPONSE']._serialized_end=195
  _globals['_GETSIZEREQUEST']._serialized_start=197
  _globals['_GETSIZEREQUEST']._serialized_end=213
  _globals['_GETSIZERESPONSE']._serialized_start=215
  _globals['_GETSIZERESPONSE']._serialized_end=246
  _globals['_DATABASE']._serialized_start=249
  _globals['_DATABASE']._serialized_end=469
# @@protoc_insertion_point(module_scope)
